#!/usr/bin/env python3
"""Regenerate `agent-comms/INDEX.md` from in-flight comm files.

Scans agent-comms/{tasks,handoffs,verifications,findings,questions,decisions,history}/
for *.md files, parses minimal YAML-style frontmatter, and writes a grouped
index. Stdlib only.

Usage (from repo root):

    python3 tools/regen_comms_index.py

Idempotent; safe to re-run. INDEX.md is overwritten in place.
"""

from __future__ import annotations

import datetime as dt
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
COMMS_DIR = REPO_ROOT / "agent-comms"
INDEX_PATH = COMMS_DIR / "INDEX.md"

TRANSIENT_CHANNELS = ("tasks", "handoffs", "verifications", "findings", "questions")
RECENT_DAYS = 7


def parse_frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end < 0:
        return {}
    fm: dict[str, str] = {}
    for line in text[4:end].splitlines():
        stripped = line.rstrip()
        if not stripped or stripped.lstrip().startswith("#"):
            continue
        if ":" not in stripped:
            continue
        key, _, value = stripped.partition(":")
        fm[key.strip()] = value.strip()
    return fm


def scan(channel: str) -> list[tuple[Path, dict[str, str]]]:
    folder = COMMS_DIR / channel
    if not folder.is_dir():
        return []
    out: list[tuple[Path, dict[str, str]]] = []
    for p in sorted(folder.glob("*.md")):
        out.append((p, parse_frontmatter(p)))
    return out


def entry_line(path: Path, fm: dict[str, str]) -> str:
    rel = path.relative_to(COMMS_DIR)
    slug = fm.get("slug", path.stem)
    frm = fm.get("from", "?")
    to = fm.get("to", "?")
    return f"- [{path.name}](./{rel}) — `{frm} → {to}` ({slug})"


def by_status(entries: list[tuple[Path, dict[str, str]]], target: str) -> list[tuple[Path, dict[str, str]]]:
    return [(p, fm) for p, fm in entries if fm.get("status", "").lower() == target]


def within_recent_days(entries: list[tuple[Path, dict[str, str]]]) -> list[tuple[Path, dict[str, str]]]:
    cutoff = dt.date.today() - dt.timedelta(days=RECENT_DAYS)
    keep: list[tuple[Path, dict[str, str]]] = []
    for p, fm in entries:
        raw = fm.get("created") or fm.get("date") or ""
        try:
            when = dt.date.fromisoformat(raw[:10])
        except ValueError:
            continue
        if when >= cutoff:
            keep.append((p, fm))
    return keep


def section(title: str, items: list[tuple[Path, dict[str, str]]]) -> list[str]:
    lines = [f"## {title}"]
    if not items:
        lines.append("_(none)_")
    else:
        for p, fm in items:
            lines.append(entry_line(p, fm))
    lines.append("")
    return lines


def render() -> str:
    transient: list[tuple[Path, dict[str, str]]] = []
    for ch in TRANSIENT_CHANNELS:
        transient.extend(scan(ch))

    in_progress = by_status(transient, "in-progress")
    pending = by_status(transient, "pending")
    blocked = by_status(transient, "blocked")

    questions_all = scan("questions")
    open_questions = [(p, fm) for p, fm in questions_all if fm.get("status", "").lower() != "resolved"]

    decisions_recent = within_recent_days(scan("decisions"))
    history_recent = within_recent_days(scan("history"))

    today = dt.date.today().isoformat()
    lines: list[str] = [
        "# Agent Comms Index",
        "",
        "Auto-generated by `tools/regen_comms_index.py`. Do not hand-edit.",
        "",
        f"Last regenerated: {today}",
        "",
    ]
    lines += section("In progress", in_progress)
    lines += section("Pending", pending)
    lines += section("Blocked", blocked)
    lines += section("Open questions", open_questions)
    lines += section(f"Recent decisions (last {RECENT_DAYS} days)", decisions_recent)
    lines += section(f"Recent history (last {RECENT_DAYS} days)", history_recent)
    return "\n".join(lines)


def main() -> int:
    if not COMMS_DIR.is_dir():
        print(f"agent-comms/ not found at {COMMS_DIR}", file=sys.stderr)
        return 2
    INDEX_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {INDEX_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
